import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import ggplot
import plotly

#import pygal
#import altair
#import geoplotlib


# Matplotlib. Matplotlib Python Library is used to generate simple yet powerful visualizations. ...
# Seaborn. ...
# ggplot. ...
# Bokeh. ...
# Plotly. ...
# Pygal. ...
# Altair. ...
# Geoplotlib
